---
AWSTemplateFormatVersion: "2010-09-09"
Description: "This is my EC2 stack"
Resources:
  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-south-1a
      ImageId: ami-02e94b011299ef128 
      InstanceType: t2.micro
      KeyName: my-devops
      SecurityGroupIds: 
        - sg-0707326786ee34e50  
